package com.ijustyce.health.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.ijustyce.health.model.User;
import com.ijustyce.health.model.Record;

import com.ijustyce.health.model.UserDao;
import com.ijustyce.health.model.RecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig recordDaoConfig;

    private final UserDao userDao;
    private final RecordDao recordDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        recordDaoConfig = daoConfigMap.get(RecordDao.class).clone();
        recordDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        recordDao = new RecordDao(recordDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Record.class, recordDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        recordDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public RecordDao getRecordDao() {
        return recordDao;
    }

}
