package com.lzhplus.lzh.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BRAND_DB".
 */
public class BrandDb {

    private Integer brandId;
    private Integer since;
    private Integer cityId;
    private Integer provinceId;
    private Integer operationType;
    private String brandName;
    private String brandLogoImg;
    private String bigLogoImg;
    private String brandTitle;
    private String brandDesc;
    private long id;

    public BrandDb() {
    }

    public BrandDb(long id) {
        this.id = id;
    }

    public BrandDb(Integer brandId, Integer since, Integer cityId, Integer provinceId, Integer operationType, String brandName, String brandLogoImg, String bigLogoImg, String brandTitle, String brandDesc, long id) {
        this.brandId = brandId;
        this.since = since;
        this.cityId = cityId;
        this.provinceId = provinceId;
        this.operationType = operationType;
        this.brandName = brandName;
        this.brandLogoImg = brandLogoImg;
        this.bigLogoImg = bigLogoImg;
        this.brandTitle = brandTitle;
        this.brandDesc = brandDesc;
        this.id = id;
    }

    public Integer getBrandId() {
        return brandId;
    }

    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    public Integer getSince() {
        return since;
    }

    public void setSince(Integer since) {
        this.since = since;
    }

    public Integer getCityId() {
        return cityId;
    }

    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    public Integer getProvinceId() {
        return provinceId;
    }

    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    public Integer getOperationType() {
        return operationType;
    }

    public void setOperationType(Integer operationType) {
        this.operationType = operationType;
    }

    public String getBrandName() {
        return brandName;
    }

    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    public String getBrandLogoImg() {
        return brandLogoImg;
    }

    public void setBrandLogoImg(String brandLogoImg) {
        this.brandLogoImg = brandLogoImg;
    }

    public String getBigLogoImg() {
        return bigLogoImg;
    }

    public void setBigLogoImg(String bigLogoImg) {
        this.bigLogoImg = bigLogoImg;
    }

    public String getBrandTitle() {
        return brandTitle;
    }

    public void setBrandTitle(String brandTitle) {
        this.brandTitle = brandTitle;
    }

    public String getBrandDesc() {
        return brandDesc;
    }

    public void setBrandDesc(String brandDesc) {
        this.brandDesc = brandDesc;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

}
