package com.lzhplus.lzh.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CITY_DB".
 */
public class CityDb {

    private long id;
    private Integer cityId;
    private Integer cityLevel;
    private String cityName;
    private String pinyin;
    private String pyFirstChar;
    private Integer pCityId;

    public CityDb() {
    }

    public CityDb(long id) {
        this.id = id;
    }

    public CityDb(long id, Integer cityId, Integer cityLevel, String cityName, String pinyin, String pyFirstChar, Integer pCityId) {
        this.id = id;
        this.cityId = cityId;
        this.cityLevel = cityLevel;
        this.cityName = cityName;
        this.pinyin = pinyin;
        this.pyFirstChar = pyFirstChar;
        this.pCityId = pCityId;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Integer getCityId() {
        return cityId;
    }

    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    public Integer getCityLevel() {
        return cityLevel;
    }

    public void setCityLevel(Integer cityLevel) {
        this.cityLevel = cityLevel;
    }

    public String getCityName() {
        return cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    public String getPinyin() {
        return pinyin;
    }

    public void setPinyin(String pinyin) {
        this.pinyin = pinyin;
    }

    public String getPyFirstChar() {
        return pyFirstChar;
    }

    public void setPyFirstChar(String pyFirstChar) {
        this.pyFirstChar = pyFirstChar;
    }

    public Integer getPCityId() {
        return pCityId;
    }

    public void setPCityId(Integer pCityId) {
        this.pCityId = pCityId;
    }

}
