package com.lzhplus.lzh.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.lzhplus.lzh.db.BrandDb;
import com.lzhplus.lzh.db.CityDb;

import com.lzhplus.lzh.db.BrandDbDao;
import com.lzhplus.lzh.db.CityDbDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig brandDbDaoConfig;
    private final DaoConfig cityDbDaoConfig;

    private final BrandDbDao brandDbDao;
    private final CityDbDao cityDbDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        brandDbDaoConfig = daoConfigMap.get(BrandDbDao.class).clone();
        brandDbDaoConfig.initIdentityScope(type);

        cityDbDaoConfig = daoConfigMap.get(CityDbDao.class).clone();
        cityDbDaoConfig.initIdentityScope(type);

        brandDbDao = new BrandDbDao(brandDbDaoConfig, this);
        cityDbDao = new CityDbDao(cityDbDaoConfig, this);

        registerDao(BrandDb.class, brandDbDao);
        registerDao(CityDb.class, cityDbDao);
    }
    
    public void clear() {
        brandDbDaoConfig.getIdentityScope().clear();
        cityDbDaoConfig.getIdentityScope().clear();
    }

    public BrandDbDao getBrandDbDao() {
        return brandDbDao;
    }

    public CityDbDao getCityDbDao() {
        return cityDbDao;
    }

}
